import { About } from '@/components/About'
import { Footer } from '@/components/Footer'
import { Hero } from '@/components/Hero'
import { Navbar } from '@/components/Navbar'
import { Particle } from '@/components/Particles'
import { Possibilities } from '@/components/Possibilities'
import { Services } from '@/components/Services'
import Head from 'next/head'


export default function Home() {

  return (
    <>
      <Head>
        <title>GrowthFarm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className="">
          <div style={{ background: "rgb(4,12,24)", background: "radial-gradient(circle at 100% 30%, rgba(13,48,88,0.7) 0.2%, transparent 40%),radial-gradient(circle at 25% 10%, rgba(13,48,88,0.6), transparent 20%),radial-gradient(circle at 50% 50%,rgba(4,12,24,1), rgba(4,12,24,1) 100%)", }}>
            {/* <Particle/> */}
            <Navbar />
            <Hero />
            <Services />
            <About />
          </div>
          <Possibilities />
          <Footer />
        </div>
      </main>
    </>
  )
}
